In [3]:
import numpy as np # linear algebra
import pandas as pd 

import os

directory_path = r'C:\Users\visha\Downloads\Fake_News_detector Project\Fake_News_Detector_NLP\data'

for dirname, _, filenames in os.walk(directory_path):
    for filename in filenames:
        print(os.path.join(dirname, filename))

C:\Users\visha\Downloads\Fake_News_detector Project\Fake_News_Detector_NLP\data\submit.csv
C:\Users\visha\Downloads\Fake_News_detector Project\Fake_News_Detector_NLP\data\test.csv
C:\Users\visha\Downloads\Fake_News_detector Project\Fake_News_Detector_NLP\data\train.csv


In [4]:
df=pd.read_csv(r'C:\Users\visha\Downloads\Fake_News_detector Project\Fake_News_Detector_NLP\data\train.csv')

In [5]:
df.head()

id                                              title              author   
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus  \
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [6]:
df.shape

(20800, 5)

In [7]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [10]:
X=df.drop('label',axis=1)
y=df['label']

In [11]:
y.shape

(18285,)

In [12]:
message=X.copy()

In [13]:
message.columns

Index(['id', 'title', 'author', 'text'], dtype='object')

In [14]:
message.title[0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [15]:
!pip install nltk
import nltk
import re
from nltk.corpus import stopwords


[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [16]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\visha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [17]:
from nltk.stem.porter import PorterStemmer

In [18]:
ps=PorterStemmer()
corpus=[]
for i in range(0,8000):
    ele=re.sub('[^a-zA-Z]',' ',message.title.iloc[i])
    ele=ele.lower()
    ele=ele.split()
    ele=[ps.stem(word) for word in ele if not word in stopwords.words('english')]
    ele=' '.join(ele)
    corpus.append(ele)

In [19]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [20]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [21]:
from tensorflow.keras.preprocessing.text import one_hot
voc_size=5000

In [22]:
onehot_rep=[one_hot(word,voc_size) for word in corpus]
onehot_rep

[[4192, 3789, 4768, 4052, 1424, 4203, 1880, 3050, 3159, 1577],
 [782, 2041, 2209, 3855, 1916, 1977, 4343],
 [1717, 1998, 3643, 180],
 [3438, 4257, 869, 1515, 3446, 245],
 [2519, 1916, 3615, 2029, 1316, 3621, 1916, 634, 1973, 2115],
 [4258,
  3971,
  245,
  4766,
  3054,
  1749,
  3541,
  2318,
  4278,
  4952,
  902,
  4769,
  3312,
  2780,
  4343],
 [1766, 715, 1721, 4362, 4673, 4755, 435, 3580, 3244, 1605, 972],
 [30, 2315, 1801, 1474, 1530, 4540, 1749, 2936, 3244, 1605, 972],
 [4440, 2723, 2199, 1452, 3757, 1348, 4986, 1015, 1749, 3150],
 [3038, 2673, 1553, 230, 4916, 2295, 4548, 2747],
 [3380, 769, 3744, 2847, 4291, 1379, 3976, 2643, 964, 4739, 793],
 [1515, 685, 1424, 1348, 1749, 1530],
 [2620, 3412, 4308, 1535, 3512, 1487, 3471, 4868, 4527],
 [4524, 285, 3023, 3340, 1094, 1154, 3384, 3244, 1605, 972],
 [936, 954, 3462, 3281, 519, 3244, 1605, 972],
 [940, 177, 4900, 245, 4934, 3321, 1199, 4572, 3697, 142],
 [4835, 548, 2041],
 [3789, 4810, 3666, 4549, 1749, 4734, 2426, 4343],
 [635

In [23]:
print(corpus[3])
print(onehot_rep[3])

civilian kill singl us airstrik identifi
[3438, 4257, 869, 1515, 3446, 245]


In [24]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [25]:
sent_maxlen=20
padding_data=pad_sequences(onehot_rep,padding='post',maxlen=sent_maxlen)
padding_data

array([[4192, 3789, 4768, ...,    0,    0,    0],
       [ 782, 2041, 2209, ...,    0,    0,    0],
       [1717, 1998, 3643, ...,    0,    0,    0],
       ...,
       [1908, 4517,  925, ...,    0,    0,    0],
       [4440, 1974, 2903, ...,    0,    0,    0],
       [3268, 2940, 2238, ...,    0,    0,    0]])

In [26]:
padding_data[1]

array([ 782, 2041, 2209, 3855, 1916, 1977, 4343,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [28]:
#Create a model with embedding
vector_len=40
model=Sequential()
model.add(Embedding(voc_size,vector_len,input_length=sent_maxlen))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [30]:
len(padding_data),y.shape

(8000, (18285,))

In [31]:
y=y[:8000]

In [32]:
y.shape

(8000,)

In [33]:
X_final=np.array(padding_data)
y_final=np.array(y)

In [34]:
print(X_final.shape,y_final.shape)

(8000, 20) (8000,)


In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [36]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
84/84 [==============================] - 4s 20ms/step - loss: 0.4436 - accuracy: 0.7659 - val_loss: 0.2183 - val_accuracy: 0.9072
Epoch 2/10
84/84 [==============================] - 1s 14ms/step - loss: 0.1605 - accuracy: 0.9382 - val_loss: 0.2083 - val_accuracy: 0.9144
Epoch 3/10
84/84 [==============================] - 1s 14ms/step - loss: 0.0931 - accuracy: 0.9700 - val_loss: 0.2355 - val_accuracy: 0.9193
Epoch 4/10
84/84 [==============================] - 1s 14ms/step - loss: 0.0576 - accuracy: 0.9799 - val_loss: 0.2618 - val_accuracy: 0.9117
Epoch 5/10
84/84 [==============================] - 1s 14ms/step - loss: 0.0356 - accuracy: 0.9879 - val_loss: 0.3139 - val_accuracy: 0.9152
Epoch 6/10
84/84 [==============================] - 1s 14ms/step - loss: 0.0201 - accuracy: 0.9946 - val_loss: 0.3316 - val_accuracy: 0.9064
Epoch 7/10
84/84 [==============================] - 1s 15ms/step - loss: 0.0089 - accuracy: 0.9979 - val_loss: 0.4797 - val_accuracy: 0.9053
Epoch 8/10
84

In [37]:
y_pred=model.predict(X_test)

83/83 [==============================] - 1s 3ms/step


In [38]:
y_pred=np.where(y_pred>0.5,1,0)

In [39]:
from sklearn.metrics import confusion_matrix

In [40]:
confusion_matrix(y_test,y_pred)

array([[1417,  100],
       [ 171,  952]], dtype=int64)

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8973484848484848

In [42]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.93      0.91      1517
           1       0.90      0.85      0.88      1123

    accuracy                           0.90      2640
   macro avg       0.90      0.89      0.89      2640
weighted avg       0.90      0.90      0.90      2640



In [43]:
model.save_weights('trained_model_weights.h5')